import { LineChart, Trophy, Star, Wallet, Calendar, Tag } from "lucide-react";

export const statisticsStatCardsData = [
  {
    id: 1,
    title: "Year-over-Year Growth",
    value: "+15.2%",
    change: "Current vs last year",
    icon: <LineChart className="w-5 h-5 text-[#10B981]" />,
    iconBgColor: "bg-[#D1FAE5]",
    iconShadowColor: "",
    cardStyle: "bg-gradient-to-b from-[#10B981]/[13%] to-[#10B981]/[3%]",
  },
  {
    id: 2,
    title: "Top Employee (Month)",
    value: "Sarah J.",
    change: "Highest client retention",
    icon: <Trophy className="w-5 h-5 text-[#F59E0B]" />,
    iconBgColor: "bg-[#FEF3C7]",
    iconShadowColor: "",
    cardStyle: "bg-gradient-to-b from-[#F59E0B]/[13%] to-[#F59E0B]/[3%]",
  },
  {
    id: 3,
    title: "Client Satisfaction",
    value: "4.9/5",
    change: "Based on 142 reviews",
    icon: <Star className="w-5 h-5 text-[#3B82F6]" />,
    iconBgColor: "bg-[#DBEAFE]",
    iconShadowColor: "",
    cardStyle: "bg-gradient-to-b from-[#3B82F6]/[13%] to-[#3B82F6]/[3%]",
  },
  {
    id: 4,
    title: "Appointments Completed",
    value: "45",
    change: "Last 30-days",
    icon: <Wallet className="w-5 h-5 text-[#635BFF]" />,
    iconBgColor: "bg-[#EEF2FF]",
    iconShadowColor: "",
    cardStyle: "bg-gradient-to-b from-[#635BFF]/[13%] to-[#635BFF]/[3%]",
  },
  {
    id: 5,
    title: "Appointments Book Now",
    value: "52",
    change: "Last 30-days",
    icon: <Calendar className="w-5 h-5 text-[#14B8A6]" />,
    iconBgColor: "bg-[#CCFBF1]",
    iconShadowColor: "",
    cardStyle: "bg-gradient-to-b from-[#14B8A6]/[13%] to-[#14B8A6]/[3%]",
  },
  {
    id: 6,
    title: "Average Ticket",
    value: "€ 100",
    change: "Average spend",
    icon: <Tag className="w-5 h-5 text-[#22C55E]" />,
    iconBgColor: "bg-[#DCFCE7]",
    iconShadowColor: "",
    cardStyle: "bg-gradient-to-b from-[#22C55E]/[13%] to-[#22C55E]/[3%]",
  },
];
