export interface MemberData {
    id: string;
    name: string;
    email: string;
    role: "Manager" | "Staff" | "Accountant";
    status: "Active" | "Pending" | "Inactive";
    employmentStatus: string;
    contractType: "Full Time" | "Part Time" | "Stage" | "Vat collaboration";
    lastActive: string;
    avatarUrl: string;
    avatarBg: string;
}

export const initialMembers: MemberData[] = [
    { id: "1", name: "Maria Rodriguez", email: "maria@beautywellness.com", role: "Manager", status: "Active", employmentStatus: "Currently Hired", contractType: "Full Time", lastActive: "1h ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maria1&backgroundColor=fce7f3", avatarBg: "bg-[#FCE7F3]" },
    { id: "2", name: "Sarah Connor", email: "sarah@beautywellness.com", role: "Staff", status: "Pending", employmentStatus: "Currently Hired", contractType: "Part Time", lastActive: "2h ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah2&backgroundColor=e2e8f0", avatarBg: "bg-[#E2E8F0]" },
    { id: "3", name: "John Smith", email: "john@beautywellness.com", role: "Staff", status: "Active", employmentStatus: "Currently Hired", contractType: "Full Time", lastActive: "3h ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=John3&backgroundColor=ccfbf1", avatarBg: "bg-[#CCFBF1]" },
    { id: "4", name: "Emma Watson", email: "emma@beautywellness.com", role: "Accountant", status: "Active", employmentStatus: "Currently Hired", contractType: "Stage", lastActive: "1d ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emma4&backgroundColor=fee2e2", avatarBg: "bg-[#FEE2E2]" },
    { id: "5", name: "Oliver Twist", email: "oliver@beautywellness.com", role: "Staff", status: "Active", employmentStatus: "Currently Hired", contractType: "Vat collaboration", lastActive: "5m ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Oliver5&backgroundColor=fce7f3", avatarBg: "bg-[#FCE7F3]" },
    { id: "6", name: "Isabella Ross", email: "isabella@beautywellness.com", role: "Manager", status: "Active", employmentStatus: "Currently Hired", contractType: "Full Time", lastActive: "10m ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella6&backgroundColor=ccfbf1", avatarBg: "bg-[#CCFBF1]" },
    { id: "7", name: "William Hunt", email: "william@beautywellness.com", role: "Staff", status: "Pending", employmentStatus: "Currently Hired", contractType: "Part Time", lastActive: "1h ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=William7&backgroundColor=fee2e2", avatarBg: "bg-[#FEE2E2]" },
    { id: "8", name: "Sophia Loren", email: "sophia@beautywellness.com", role: "Staff", status: "Inactive", employmentStatus: "Out of Team: 02/02/2025", contractType: "Full Time", lastActive: "1w ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sophia8&backgroundColor=e2e8f0", avatarBg: "bg-[#E2E8F0]" },
    { id: "9", name: "Lucas Black", email: "lucas@beautywellness.com", role: "Accountant", status: "Inactive", employmentStatus: "Out of Team: 02/02/2025", contractType: "Full Time", lastActive: "2w ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas9&backgroundColor=e2e8f0", avatarBg: "bg-[#E2E8F0]" },
    { id: "10", name: "Mia Wong", email: "mia@beautywellness.com", role: "Staff", status: "Active", employmentStatus: "Currently Hired", contractType: "Part Time", lastActive: "30m ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mia10&backgroundColor=ccfbf1", avatarBg: "bg-[#CCFBF1]" },
    { id: "11", name: "James Bond", email: "james@beautywellness.com", role: "Manager", status: "Active", employmentStatus: "Currently Hired", contractType: "Full Time", lastActive: "1h ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=James11&backgroundColor=fce7f3", avatarBg: "bg-[#FCE7F3]" },
    { id: "12", name: "Amelia Earhart", email: "amelia@beautywellness.com", role: "Staff", status: "Active", employmentStatus: "Currently Hired", contractType: "Part Time", lastActive: "2h ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amelia12&backgroundColor=e2e8f0", avatarBg: "bg-[#E2E8F0]" },
    { id: "13", name: "Benjamin Button", email: "benjamin@beautywellness.com", role: "Staff", status: "Pending", employmentStatus: "Currently Hired", contractType: "Stage", lastActive: "4h ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Benjamin13&backgroundColor=fee2e2", avatarBg: "bg-[#FEE2E2]" },
    { id: "14", name: "Charlotte Bronte", email: "charlotte@beautywellness.com", role: "Staff", status: "Active", employmentStatus: "Currently Hired", contractType: "Vat collaboration", lastActive: "5h ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Charlotte14&backgroundColor=ccfbf1", avatarBg: "bg-[#CCFBF1]" },
    { id: "15", name: "Elijah Wood", email: "elijah@beautywellness.com", role: "Staff", status: "Inactive", employmentStatus: "Out of Team: 01/15/2025", contractType: "Full Time", lastActive: "1m ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Elijah15&backgroundColor=e2e8f0", avatarBg: "bg-[#E2E8F0]" },
    { id: "16", name: "Harper Lee", email: "harper@beautywellness.com", role: "Manager", status: "Active", employmentStatus: "Currently Hired", contractType: "Full Time", lastActive: "1h ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Harper16&backgroundColor=fce7f3", avatarBg: "bg-[#FCE7F3]" },
    { id: "17", name: "Alexander the Great", email: "alexander@beautywellness.com", role: "Staff", status: "Pending", employmentStatus: "Currently Hired", contractType: "Part Time", lastActive: "2h ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alexander17&backgroundColor=fee2e2", avatarBg: "bg-[#FEE2E2]" },
    { id: "18", name: "Evelyn Salt", email: "evelyn@beautywellness.com", role: "Accountant", status: "Active", employmentStatus: "Currently Hired", contractType: "Stage", lastActive: "3h ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Evelyn18&backgroundColor=ccfbf1", avatarBg: "bg-[#CCFBF1]" },
    { id: "19", name: "Daniel Craig", email: "daniel@beautywellness.com", role: "Staff", status: "Active", employmentStatus: "Currently Hired", contractType: "Vat collaboration", lastActive: "4h ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Daniel19&backgroundColor=e2e8f0", avatarBg: "bg-[#E2E8F0]" },
    { id: "20", name: "Abigail Adams", email: "abigail@beautywellness.com", role: "Staff", status: "Inactive", employmentStatus: "Out of Team: 12/31/2024", contractType: "Full Time", lastActive: "5h ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Abigail20&backgroundColor=fce7f3", avatarBg: "bg-[#FCE7F3]" },
    { id: "21", name: "Michael Jordan", email: "michael@beautywellness.com", role: "Manager", status: "Active", employmentStatus: "Currently Hired", contractType: "Full Time", lastActive: "1h ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael21&backgroundColor=ccfbf1", avatarBg: "bg-[#CCFBF1]" },
    { id: "22", name: "Emily Blunt", email: "emily@beautywellness.com", role: "Staff", status: "Pending", employmentStatus: "Currently Hired", contractType: "Part Time", lastActive: "2h ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily22&backgroundColor=fee2e2", avatarBg: "bg-[#FEE2E2]" },
    { id: "23", name: "Matthew McConaughey", email: "matthew@beautywellness.com", role: "Staff", status: "Active", employmentStatus: "Currently Hired", contractType: "Stage", lastActive: "3h ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Matthew23&backgroundColor=e2e8f0", avatarBg: "bg-[#E2E8F0]" },
    { id: "24", name: "Avery Brooks", email: "avery@beautywellness.com", role: "Staff", status: "Active", employmentStatus: "Currently Hired", contractType: "Vat collaboration", lastActive: "4h ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Avery24&backgroundColor=fce7f3", avatarBg: "bg-[#FCE7F3]" },
    { id: "25", name: "David Beckham", email: "david@beautywellness.com", role: "Staff", status: "Inactive", employmentStatus: "Out of Team: 11/30/2024", contractType: "Full Time", lastActive: "5h ago", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=David25&backgroundColor=ccfbf1", avatarBg: "bg-[#CCFBF1]" },
];